// <auto-generated />
namespace Trash_Collector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class latlngMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(latlngMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201609191734261_latlngMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
